# Generated by Copilot
.PHONY: help init plan apply destroy clean validate fmt check-fmt lint

# Default target
help: ## Show this help message
	@echo "DevOps Future NG - EKS Infrastructure"
	@echo "====================================="
	@echo ""
	@echo "Available targets:"
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

init: ## Initialize Terraform
	terraform init

validate: ## Validate Terraform configuration
	terraform validate

fmt: ## Format Terraform files
	terraform fmt -recursive

check-fmt: ## Check if Terraform files are properly formatted
	terraform fmt -check -recursive

plan: ## Create Terraform plan
	terraform plan -out=tfplan

apply: ## Apply Terraform plan
	terraform apply tfplan

deploy: ## Full deployment (init, plan, apply, configure)
	@echo "🚀 Starting full deployment..."
	./deploy.sh

destroy: ## Destroy infrastructure
	@echo "⚠️  This will destroy all infrastructure!"
	@read -p "Are you sure? (y/N): " confirm && [ "$$confirm" = "y" ] || exit 1
	terraform destroy

clean: ## Clean temporary files
	rm -f tfplan
	rm -f kubeconfig.yaml

outputs: ## Show Terraform outputs
	terraform output

kubeconfig: ## Update kubectl configuration
	aws eks --region us-west-2 update-kubeconfig --name $$(terraform output -raw cluster_id)

nodes: ## Show cluster nodes
	kubectl get nodes

pods: ## Show all pods
	kubectl get pods --all-namespaces

cluster-info: ## Show cluster information
	kubectl cluster-info

lint: ## Run tflint (requires tflint to be installed)
	@if command -v tflint >/dev/null 2>&1; then \
		tflint; \
	else \
		echo "tflint not installed. Install with: brew install tflint"; \
	fi
