# Generated by Copilot
output "vpc_id" {
  description = "ID of the VPC"
  value       = module.vpc.vpc_id
}

output "vpc_cidr_block" {
  description = "CIDR block of the VPC"
  value       = module.vpc.vpc_cidr_block
}

output "private_subnet_ids" {
  description = "IDs of the private subnets"
  value       = module.vpc.private_subnet_ids
}

output "public_subnet_ids" {
  description = "IDs of the public subnets"
  value       = module.vpc.public_subnet_ids
}

output "cluster_id" {
  description = "EKS cluster ID"
  value       = module.eks.cluster_id
}

output "cluster_arn" {
  description = "EKS cluster ARN"
  value       = module.eks.cluster_arn
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane"
  value       = module.eks.cluster_security_group_id
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = module.eks.cluster_certificate_authority_data
}

output "cluster_version" {
  description = "The Kubernetes version for the cluster"
  value       = module.eks.cluster_version
}

output "node_groups" {
  description = "Map of node groups and their attributes"
  value       = module.eks.node_groups
}

output "kubeconfig_filename" {
  description = "Path to the generated kubeconfig file"
  value       = "${path.module}/kubeconfig.yaml"
}

output "configure_kubectl" {
  description = "Configure kubectl"
  value       = "aws eks --region ${var.aws_region} update-kubeconfig --name ${module.eks.cluster_name}"
}

# Logging outputs
output "vpc_flow_logs_log_group" {
  description = "VPC Flow Logs CloudWatch Log Group"
  value       = module.vpc.vpc_flow_logs_log_group_name
}

output "eks_cluster_log_group" {
  description = "EKS Cluster CloudWatch Log Group"
  value       = module.eks.cluster_log_group_name
}

output "logging_enabled" {
  description = "Summary of enabled logging"
  value = {
    vpc_flow_logs    = "Enabled - CloudWatch Logs"
    eks_cluster_logs = join(", ", module.eks.cluster_logging_enabled)
    log_retention    = "VPC: 14 days, EKS: 30 days"
  }
}
