# Generated by Copilot
variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-west-2"
}

variable "aws_account_id" {
  description = "AWS Account ID"
  type        = string
  default     = "974654858447"
}

variable "name_prefix" {
  description = "Name prefix for all resources"
  type        = string
  default     = "devops-future_ng"
}

variable "vpc_cidr" {
  description = "CIDR block for VPC"
  type        = string
  default     = "10.0.0.0/16"
}

variable "cluster_version" {
  description = "Kubernetes version for EKS cluster"
  type        = string
  default     = "1.32"
}

variable "node_group_instance_types" {
  description = "Instance types for EKS node group"
  type        = list(string)
  default     = ["t3.medium"]
}

variable "node_group_capacity_type" {
  description = "Capacity type for node group"
  type        = string
  default     = "ON_DEMAND"
}

variable "node_group_desired_size" {
  description = "Desired size of the node group"
  type        = number
  default     = 3
}

variable "node_group_max_size" {
  description = "Maximum size of the node group"
  type        = number
  default     = 6
}

variable "node_group_min_size" {
  description = "Minimum size of the node group"
  type        = number
  default     = 3
}

variable "default_tags" {
  description = "Default tags to apply to all resources"
  type        = map(string)
  default = {
    Project     = "DevOps Future NG"
    Environment = "development"
    Owner       = "Platform Team"
    ManagedBy   = "Terraform"
  }
}
