# Generated by Copilot
output "cluster_id" {
  description = "EKS cluster ID"
  value       = aws_eks_cluster.main.id
}

output "cluster_arn" {
  description = "EKS cluster ARN"
  value       = aws_eks_cluster.main.arn
}

output "cluster_name" {
  description = "EKS cluster name"
  value       = aws_eks_cluster.main.name
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = aws_eks_cluster.main.endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane"
  value       = aws_eks_cluster.main.vpc_config[0].cluster_security_group_id
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = aws_eks_cluster.main.certificate_authority[0].data
}

output "cluster_version" {
  description = "The Kubernetes version for the cluster"
  value       = aws_eks_cluster.main.version
}

output "cluster_oidc_issuer_url" {
  description = "The URL on the EKS cluster OIDC Issuer"
  value       = aws_eks_cluster.main.identity[0].oidc[0].issuer
}

output "node_groups" {
  description = "Map of node groups and their attributes"
  value = {
    for idx, ng in aws_eks_node_group.main : ng.node_group_name => {
      arn            = ng.arn
      status         = ng.status
      capacity_type  = ng.capacity_type
      instance_types = ng.instance_types
      scaling_config = ng.scaling_config
    }
  }
}

output "cluster_security_group_ids" {
  description = "Security group IDs attached to the EKS cluster"
  value       = [aws_security_group.cluster.id]
}

output "node_security_group_id" {
  description = "Security group ID attached to the EKS node group"
  value       = aws_security_group.node_group.id
}

output "cluster_log_group_name" {
  description = "CloudWatch Log Group name for EKS cluster logs"
  value       = aws_cloudwatch_log_group.eks_cluster.name
}

output "cluster_log_group_arn" {
  description = "CloudWatch Log Group ARN for EKS cluster logs"
  value       = aws_cloudwatch_log_group.eks_cluster.arn
}

output "cluster_logging_enabled" {
  description = "List of enabled cluster log types"
  value       = aws_eks_cluster.main.enabled_cluster_log_types
}
