# Generated by Copilot
variable "name_prefix" {
  description = "Name prefix for all resources"
  type        = string
}

variable "cluster_version" {
  description = "Kubernetes version for EKS cluster"
  type        = string
}

variable "vpc_id" {
  description = "VPC ID where EKS cluster will be deployed"
  type        = string
}

variable "private_subnet_ids" {
  description = "List of private subnet IDs"
  type        = list(string)
}

variable "public_subnet_ids" {
  description = "List of public subnet IDs"
  type        = list(string)
}

variable "node_group_instance_types" {
  description = "Instance types for EKS node group"
  type        = list(string)
}

variable "node_group_capacity_type" {
  description = "Capacity type for node group"
  type        = string
}

variable "node_group_desired_size" {
  description = "Desired size of the node group"
  type        = number
}

variable "node_group_max_size" {
  description = "Maximum size of the node group"
  type        = number
}

variable "node_group_min_size" {
  description = "Minimum size of the node group"
  type        = number
}

variable "default_tags" {
  description = "Default tags to apply to all resources"
  type        = map(string)
}
